### ISSUE TITLE
Provide integration with external kafka topics to provide sort of Kafka Streams alternative.

### ISSUE THREAD

**Issue by valdo404** [rayokota/kareldb#3]
Having a dependency to RocksDB in order to build a database reminds me that Kafka Streams is working the same way.

Would it be possible to provide streaming semantics on top of Kareldb ?
Also would it be possible to provide sort of debezium system on top of KarelDB to stream database changes to the outside ?

**Comment by rayokota** [comment]
Thanks for the questions.  For streaming, I would recommend trying KSQL (https://www.confluent.io/product/ksql/) instead.

To consume database changes, it's as easy as creating a KCache instance and implementing a custom `CacheUpdateHandler` (https://github.com/rayokota/kcache/blob/master/src/main/java/io/kcache/KafkaCache.java#L112)
