### ISSUE TITLE
cannot find class org.apache.calcite.sql.parser.parserextension.ExtensionSqlParserImpl

### ISSUE THREAD

**Issue by ltylty** [rayokota/kareldb#73]
in class org.apache.calcite.sql.ddl.ExtensionDdlExecutor 
import org.apache.calcite.sql.parser.parserextension.ExtensionSqlParserImpl.
but cannot find class ExtensionSqlParserImpl in any package.

**Comment by rayokota** [comment]
This is a generated class, try building the project with `mvn clean package`
